### ISSUE TITLE
Bug: Incorrect filename leads to error

### ISSUE THREAD

**Issue by howird** [deid84/tauri-sveltekit-admin-template#1]
- Running:
```bash
$ npm run tauri dev
```

- Gives error:
```
Failed to load url /src/lib/components/layout/Sidebar.svelte (resolved id: /home/howird/howork/tabstate-template/src/lib/components/layout/Sidebar.svelte) in /home/howird/howork/tabstate-template/src/routes/+layout.svelte. Does the file exist?
```

- This is due to incorrect case in the filename, the file `sidebar.svelte` should be renamed to `Sidebar.svelte`

**Comment by deid84** [comment]
Thank's for the feedback, I've renamed the file and pushed to the main branch.


Let me know if you'll find other issues to fix
